services:
    mysql:
        image: 'mysql:8.0'
        container_name: stulbs-mysql
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: secret
        volumes:
            - 'mysql_data:/var/lib/mysql'
    app:
        build: .
        container_name: stulbs-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
        ports:
            - '8000:9000'
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: sail
            DB_PASSWORD: secret
    nginx:
        image: 'nginx:alpine'
        container_name: stulbs-nginx
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
volumes:
    mysql_data: null
    sail-mysql:
        driver: local
